### PR TITLE
[MRG] array2hist and hist2array

### PR DESCRIPTION
**Pull request by ndawe**
- [x] implement `array2hist` and `hist2array` functions with docstrings
- [x] maintain 100% test coverage

```python
>>> from root_numpy import array2hist, hist2array
>>> import numpy as np
>>> from rootpy.plotting import Hist2D
>>> hist = Hist2D(5, 0, 1, 3, 0, 1, type='F')
>>> array = np.random.randint(0, 10, size=(7, 5))
>>> array
array([[6, 7, 8, 3, 4],
       [8, 9, 7, 6, 2],
       [2, 3, 4, 5, 2],
       [7, 6, 5, 7, 3],
       [2, 0, 5, 6, 8],
       [0, 0, 6, 5, 2],
       [2, 2, 1, 5, 4]])
>>> array2hist(array, hist)
>>> hist2array(hist) # dtype matches histogram type (D, F, I, S, C)
array([[ 9.,  7.,  6.],
       [ 3.,  4.,  5.],
       [ 6.,  5.,  7.],
       [ 0.,  5.,  6.],
       [ 0.,  6.,  5.]], dtype=float32)
>>> hist2array(hist, include_overflow=True) # overflow is excluded by default
array([[ 6.,  7.,  8.,  3.,  4.],
       [ 8.,  9.,  7.,  6.,  2.],
       [ 2.,  3.,  4.,  5.,  2.],
       [ 7.,  6.,  5.,  7.,  3.],
       [ 2.,  0.,  5.,  6.,  8.],
       [ 0.,  0.,  6.,  5.,  2.],
       [ 2.,  2.,  1.,  5.,  4.]], dtype=float32)
>>> array2 = hist2array(hist, include_overflow=True, copy=False)
>>> hist[2, 2] = -10
>>> array2 # views the same memory as hist because copy=False
array([[  6.,   7.,   8.,   3.,   4.],
       [  8.,   9.,   7.,   6.,   2.],
       [  2.,   3., -10.,   5.,   2.],
       [  7.,   6.,   5.,   7.,   3.],
       [  2.,   0.,   5.,   6.,   8.],
       [  0.,   0.,   6.,   5.,   2.],
       [  2.,   2.,   1.,   5.,   4.]], dtype=float32)
>>> hist[2, 3] = -10 # x, y, z axes correspond to axes 0, 1, 2 in numpy
>>> array2
array([[  6.,   7.,   8.,   3.,   4.],
       [  8.,   9.,   7.,   6.,   2.],
       [  2.,   3., -10., -10.,   2.],
       [  7.,   6.,   5.,   7.,   3.],
       [  2.,   0.,   5.,   6.,   8.],
       [  0.,   0.,   6.,   5.,   2.],
       [  2.,   2.,   1.,   5.,   4.]], dtype=float32)
```

### CODE REVIEW

**Comment by kratsg** [comment]
@ndawe - How does this handle errors stored in bins? What if someone used `TH1F::Sumw2()` and wanted to extract all information from the histogram in the form of numpy arrays?

**Comment by ndawe** [comment]
That will be added later. The default call will only return the bin contents but the yet to be implemented return_errors option will return the bin errors as a second return value. This way the function call isn't doing more than what is needed if only the bin contents are required. I'll also be adding a return_edges argument to return the bin edges.

**Comment by kratsg** [comment]
Awesome, few more questions if you don't mind (still learning cython and you seem magical)

- why do you need `hist.GetNBinsX() + 2`? This seems like a strange counting error. Does this include the outer two bins?
- why do you only write code for `array_hNc()`?
- are the other helper functions for things like `h1d_array` just setting the pointer for `root_hist` to point at `array` or is it copying values over?

**Comment by ndawe** [comment]
`hist.GetNBinsX() + 2` includes the underflow and overflow bins. I needed to write the `array_hNc()` functions because GetArray() on the TArrayC returns a python string (PyROOT's pythonization) since the return type is char*, but the other TArray types give you a buffer object that numpy.array is happy with. So TArrayC needed to be handled on the Cython size. The array->hist direction requires copying but hist->array doesn't need to copy. For array->hist I could not reliably have the ROOT histogram view the same memory as the numpy array (by simply pointing hist.fArray at the memory) since the numpy array owns that memory and deleting the history results in a double-delete eventually. I could hack the numpy array to release ownership but still numpy uses malloc and the ROOT histogram uses delete instead of free. I concluded there was no reliable way to have the histogram view the same memory as the numpy array for array->hist and a copy is always done.

**Comment by cbourjau** [comment]
Hello,
I just started to use numpy for my THn multidimensional histograms. Currently, I am copying my content from the histogram to the numpy array in pure python which is very slow. I took a look at your implementations of hist2array and figure that the problem with THn is that it uses TNDArray, is it not? I just wanted to ask for your opinion and experience with this before diving into this further. I suppose that in the case of THn one has no other option than to loop over the TNDArray elements and to write them into a new buffer with which numpy is happy, or am I mistaken here? Do you see other complications for extending hist2array to n dimensions? Thank you very much (for this an for all your other amazing work)!
Cheers,
Christian

**Comment by ndawe** [comment]
Yeah we will need to write specific converters for TNDArrays that will loop over the bins. It won't be as easy as TH1/2/3 but I imagine the cythonized loops will be much faster than python. Could you share your python code that does the same thing? This could really help porting it to cython in root_numpy.

**Comment by cbourjau** [comment]
Thanks for your quick reply! Here is the code I am using right now.

    def my_hist2array(hist, dtype, default_value=None):
        out = np.full([hist.GetAxis(i).GetNbins() for i in range(hist.GetNdimensions())], default_value, dtype=dtype)
        coord = np.array(range(hist.GetNdimensions()), dtype=np.int32)
        overflow_coords = np.array([hist.GetAxis(i).GetNbins() for i in range(hist.GetNdimensions())], dtype=np.int32)
        for ibin in xrange(hist.GetNbins()):
            cont = hist.GetBinContent(ibin, coord)
            if cont and np.all(coord) and np.all(coord - overflow_coords <= 0):
                out[tuple(coord-1)] = cont
        return out

As you can see, this is really just a quick hack for my needs but I hope it is still helpful!

**Comment by ndawe** [comment]
Thanks @cbourjau! This really helps. I should be able to get this into root_numpy for a new release really soon.

**Comment by cbourjau** [comment]
Fantastic! Thanks again!

**Comment by ndawe** [comment]
To be consistent with TH1/2/3 I'm going to have empty bins translate to 0 elements instead of NaN. That's the only fundamental change I'm making to your code. This can always be changed by the user with something like ``a[a==0] = np.nan``

**Comment by ndawe** [comment]
@cbourjau see the new PR #237

**Comment by ndawe** [comment]
@cbourjau comments are welcome on #237. I'll leave the PR open for a day or so before merging and making a release.

**Comment by cbourjau** [comment]
@ndawe Works splendidly and gives me a nice speed-up by 2 orders of magnitude! Thanks so much!

**Comment by ndawe** [comment]
Sweet. That's good to hear. 4.4.1 is now released.

**Pull request merged**
