### PR TITLE
Improved hist2array()

### PR DESCRIPTION
**Pull request by sdporzio**
One thing I've always found problematic is to plot a TH object in pyplot via hist2array because I don't have access to the array of bin low edges. I've made a small fix. Now the hist2array function returns two arguments.

```
    bin_array[dim]: list of numpy arrays
        A list of NumPy arrays containing the histogram bin low edges ([x,y,z])
    array : numpy array
        A NumPy array containing the histogram bin values
```

The dimension of bin_array depends on the dimension of the histogram.

This is my first pull request ever, so I deeply apologize if I have done something wrong or not according to the rules. Every suggestion, comment or proposition is extremely welcome.

### CODE REVIEW

**Comment by ndawe** [comment]
Thanks! I suggest adding an argument ``return_edges=False`` that when True the edges will be returned. This way the current behaviour is preserved.

**Comment by sdporzio** [comment]
@ndawe Good idea! I've just committed the change.

**Comment by sdporzio** [comment]
Anything else that could be added?

**Comment by ndawe** [comment]
I'll review this on the weekend. Thanks again for the contribution!

**Comment by cbourjau** [comment]
I am also quite interested in this feature. As far as I can see, this is currently implemented by looping over all the bins individually. However, TAxis provides the not so aptly called method  `TAxis::GetLowEdge(Double_t* )` which actually returns all the bins' low edges in one go. Now, as with (almost) everything ROOT related, this is not the end of the story. The lower edges of cause don't help much if we have individual bin sizes. Therefore, I suggest that the we should increase the dimensionality of `bin_array` (in the following called `edges`) in order to also accommodate for the upper edge of the last bin. How about:

```python
import ROOT
import numpy as np

h = ROOT.TH1F("name", "title", 10, 0, 1)
ax = h.GetXaxis()
# `edges` is Nbins + 1 in order to have the last bin's upper edge also
edges = np.arange(ax.GetNbins() + 1, dtype=np.double)
# load the lower edges into `edges`
ax.GetLowEdge(edges) 
# Get the upper edge of the last bin
edges[-1] = ax.GetBinUpEdge(ax.GetNbins())
print edges

>>> [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]
```

I am currently not at my work machine so I cannot make a patch right now, though.

Cheers,
Christian

**Comment by sdporzio** [comment]
@cbourjau That sounds like a good idea! I'll introduce this and push.

**Comment by cbourjau** [comment]
I needed this straight away for my work so I just implemented it myself. If we don't have to loop over all the bins, there is no need to touch the pyx files either, as far as I can see. Sorry if I now duplicated our efforts, though! I In either case, I also added a few tests which should be universal for both our implementations. 
Cheers,
Christian

**Comment by ndawe** [comment]
Yes, dumping the edges directly into a numpy array in one go is what should be done here. Much like the hist2array code that copies the underlying histogram array into the numpy array.

**Comment by ndawe** [comment]
@cbourjau would you like to open a PR?

**Comment by cbourjau** [comment]
@ndawe I just created PR #288, as you can see.

Thanks yet again for all your amazing work!

**Comment by ndawe** [comment]
Closing via #290. hist2array now optionally returns the bin edges. New release soon...

**Comment by ndawe** [comment]
This is now in 4.6.0

**Pull request closed without merging**
