### PR TITLE
List trees inside a directory

### PR DESCRIPTION
**Pull request by tdoughty1**
Base on the discussion we had in the last pull request, I've attempted to make a basic modification to allow list_trees to look inside directories.

It's still fairly simple, but the idea is to add an optional dirname argument so that you can list the trees for a single directory.  If no keyword is given, the functionality should be unchanged.

### CODE REVIEW

**Comment by tdoughty1** [comment]
Ah, apparently there's a problem with Python3.  I'll look into this and fix it.

**Comment by kratsg** [comment]
It looks like a sorting issue:

```
Lists differ: ['Tree2', 'Tree1'] != ['Tree1', 'Tree2']
```

**Comment by tdoughty1** [comment]
Yes.  I saw that.  Unfortunately it looks like the bug was a little more subtle.  I tried to switch it to a list to maintain ordering and there was some duplication using the keys in a dictionary hid.  I'm investigating it and will hope to have a fix shortly.

**Comment by tdoughty1** [comment]
Turns out the duplication was in how I wrote the test file not the function.  Now that I've fixed the test file and switched to a sorted list, it passes the full test suite.

**Comment by ndawe** [comment]
Closing with #240. The ideas here could still be useful though in setting a starting directory for the recursive listing implemented in #240.

**Pull request closed without merging**
