### PR TITLE
Optionally pass bin errors in array2hist

### PR DESCRIPTION
**Pull request by cbourjau**
This includes tests and should work for errors given with and without overflow bins.

Any comments? I just implemented this and am about to use it in my analysis. I will report back if I found any issues "in production", but hope that the passing tests are covering everything.

### CODE REVIEW

**Comment by ndawe** [comment]
Thanks @cbourjau! That test failure seems unrelated, otherwise it looks good.

**Comment by ndawe** [comment]
Restarting the unit tests after fixing the unrelated failing test (due to a change in numpy).

**Comment by ndawe** [comment]
BTW this should complement #302

**Comment by ndawe** [comment]
Tests are green now :beer:

**Comment by cbourjau** [comment]
I have used this feature a bit now and did not notice any issues. Thanks once again for all your work on this awesome package!

**Comment by ndawe** [comment]
Many thanks for this contribution! I'm merging it in :beers:

**Pull request merged**
