### PR TITLE
Append to existing tree in array2root

### PR DESCRIPTION
**Pull request by ibab**
Hi,

while working on a pandas wrapper for root_numpy ([https://github.com/ibab/root_pandas](https://github.com/ibab/root_pandas)) I noticed that `array2root` doesn't properly append to existing TTrees: the file just gets larger and larger, but only the last saved version of the tree is accessible.

```python
import numpy as np
from root_numpy import root2array, array2root

arr = np.array(np.array([1,2,3]), dtype=[('test', '<i8')])
array2root(arr, 'test.root', 'default')
array2root(arr, 'test.root', 'default')

x = root2array('test.root', 'default')
print(x)
# prints [1,2,3] instead of [1,2,3,1,2,3]
```

As far as I can tell, this can be fixed by looking for an existing tree and passing it to array2tree.

What do you think?

### CODE REVIEW

**Comment by kratsg** [comment]
I believe array2root is a single output file, when you run it twice, it
creates two outputs, the second overwriting the first. I've never used it
for streaming purposes.

**Comment by ibab** [comment]
It depends on the mode you pass to array2root.
The default is 'update', which allows you to append to the file.
The file is overwritten when passing mode='recreate'.

**Comment by ndawe** [comment]
A wrapper for pandas! Nice!

Yes, array2root just writes out a file and will overwrite an existing file (the mode keyword argument can be used to update an existing file, but a tree with the same name would just be "overwritten").

Use array2tree instead of array2root. array2tree will extend an existing tree:

```python
315 def array2tree(arr, name='tree', tree=None):
316     """Convert a numpy structured array into a ROOT TTree.
317 
318     .. warning::
319        This function is experimental. Please report problems.
320        Not all data types are supported (``np.object`` and ``np.float16``).
321 
322     Parameters
323     ----------
324     arr : array
325         A numpy structured array
326     name : str (optional, default='tree')
327         Name of the created ROOT TTree if ``tree`` is None.
328     tree : existing ROOT TTree (optional, default=None)
329         Any branch with the same name as a field in the
330         numpy array will be extended as long as the types are compatible,
331         otherwise a TypeError is raised. New branches will be created
332         and filled for all new fields.
```

**Comment by ndawe** [comment]
Although, this would be a nice feature to add. I think we should enable growing an existing TTree with array2root also. But for now, array2tree should do the job.

**Comment by ndawe** [comment]
Checking the diff and will merge.

**Comment by ndawe** [comment]
@ibab what version of Cython did you run? 0.21.2?

**Comment by ndawe** [comment]
(Sorry, originally thought this was an issue report, but then realised it is a pull request!)

**Comment by ibab** [comment]
I think I ran 0.21, but I could rerun with 0.21.2.

**Comment by ndawe** [comment]
Great, yes better to use the latest. Then I will merge.

**Comment by ibab** [comment]
Ok, I ran 0.21.2 and amended the commit.

**Comment by ndawe** [comment]
thanks!

**Comment by ibab** [comment]
Thanks! That will make stream processing of ROOT files very convenient.
And I can use array2tree in my wrapper until the next version of root_numpy is released.

**Comment by ndawe** [comment]
3.4.0 is released: https://pypi.python.org/pypi/root_numpy

**Pull request merged**
