### PR TITLE
Hist bin edges

### PR DESCRIPTION
**Pull request by cbourjau**
This is an implementation plus tests for returning the bin edges along with the bin values when calling hist2array. Details are discussed in PR #280

### CODE REVIEW

**Comment by ndawe** [comment]
Thanks! I'll start reviewing.

**Comment by ndawe** [comment]
Following those minor fixes, I think this can be merged. Thanks again for this important contribution!

**Comment by cbourjau** [comment]
Actually, I just discovered a bug. The current PR is not copying the data from the histogram but shares the memory. I'll fix this asap.

**Comment by ndawe** [comment]
Strange. Isn't GetLowEdge already copying the edges in by values here?

https://root.cern.ch/doc/master/src_2TAxis_8cxx_source.html#l00548

**Comment by cbourjau** [comment]
The problem is not for the edges, but for the actual bin content. It is probably just a simple "return" missing in _hist.py:257 and following. I have it fixed locally but would like to write some tests first. Might be next week, though.

**Comment by cbourjau** [comment]
Should be fixed now including tests

**Comment by ndawe** [comment]
Closed via #290

**Comment by ndawe** [comment]
This is now in release 4.6.0!

**Pull request closed without merging**
