### PR TITLE
[MRG] add DOI badge from zenodo.org

### PR DESCRIPTION
**Pull request by ndawe**

### CODE REVIEW

**Comment by piti118** [comment]
@ndawe Is there a way to change my affiliation on Zenodo?

**Comment by ndawe** [comment]
I'm not sure. I think Zenodo grabs this from your Github profile.

**Comment by ndawe** [comment]
If you recently updated this on Github, then the next release on Zenodo will probably have your current info.

**Comment by piti118** [comment]
Okie no problem.

**Pull request merged**
